Ordermanagementsystemdemo/Controllers/productsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Ordermanagementsystemdemo;
using System.IO;
using Ordermanagementsystemdemo.Models;

namespace Ordermanagementsystemdemo.Controllers
{
    public class productsController : Controller
    {
        
        private OrdermanagmentsystemDBEntities db = new OrdermanagmentsystemDBEntities();

        // GET: products
        public ActionResult Index()
        {
            string strUseraname = Session["name"].ToString();
            var roleid = db.users.Where(x => x.username == strUseraname).Select(x => x.roleid).FirstOrDefault();
            ViewBag.roleid = roleid;

            return View(db.products.ToList());
        }

        // GET: products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product product = db.products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: products/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: products/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( ProductModel product)
        {
            

            string FolderPath = Server.MapPath("~/images/");
            string _filename = DateTime.Now.ToString("yymmssfff") + Path.GetFileNameWithoutExtension(product.Imagepath.FileName);
            product p = new product
            {
                name = product.name,
                image = "/images/" + _filename,
                availablequentity = product.availablequentity,
                price=product.price
            };


            if (ModelState.IsValid)
            {
                
                string extension = Path.GetExtension(product.Imagepath.FileName);
                
                
                if (extension.ToLower() == ".jpg" || extension.ToLower() == ".png" || extension.ToLower() == ".jpeg")
                {
                    if (product.Imagepath.ContentLength <= 3000000)
                    {
                        db.products.Add(p);
                        if (db.SaveChanges() > 0)
                        {
                            product.Imagepath.SaveAs(FolderPath + _filename);
                            ViewBag.msg = "product saved";
                        }
                        
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ViewBag.msg = "file size not valid";
                    }
                }
            }


            return View(product);
        }
        public ActionResult Addtocart(int Id)
        {
            product pro = db.products.Where(x => x.id == Id).SingleOrDefault();
            return View(pro);

            
            
        }

        List<Cart> li = new List<Cart>();

        [HttpPost]
        public ActionResult Addtocart(product pro,string qty, int id)
        {

            product p = db.products.Where(x => x.id == id).SingleOrDefault();

           Cart c = new Cart();
   
            string strUseraname = Session["name"].ToString();
            c.productid = pro.id;
            c.customername = db.users.Where(x => x.username == strUseraname).Select(x => x.name).FirstOrDefault();
            c.productid = p.id;
            c.orderstatus = "Inprogress";
            c.price = pro.price;
            c.address = db.users.Where(x => x.username == strUseraname).Select(x => x.address).FirstOrDefault();
            
            //db.orders.Add(ordr);
            //db.SaveChanges();
            if (TempData["product"] == null)
            {
                li.Add(c);
                TempData["product"] = li;

            }
            else
            {
                List<Cart> li2 = TempData["product"] as List<Cart>;

                li2.Add(c);
                TempData["product"] = li2;
            }
            TempData.Keep();
            ViewBag.customername = c.customername;
            return RedirectToAction("Index"/*p1*/);
        }

        public ActionResult Checkout()
        {
            List<Cart> cart = TempData["product"] as List<Cart>;
            TempData.Keep();
            return View();
        }
        [HttpPost]
        public ActionResult Checkout(order odr)
        {
            string strUseraname = Session["name"].ToString();
            List<Cart> cart = TempData["product"] as List<Cart>;
            foreach (var item in cart)
            {
                
                odr.customername = item.customername;
                odr.customerid = db.users.Where(x => x.username == strUseraname).Select(x => x.id).FirstOrDefault();
                odr.orderstatus = "inprogress";
                odr.address = db.users.Where(x => x.username == strUseraname).Select(x => x.address).FirstOrDefault();
                odr.productID = item.productid;
                db.orders.Add(odr);
                db.SaveChanges();
            }
            TempData.Remove("product");
            TempData["msg"] = "Oder has been done";
            TempData.Keep();
            return RedirectToAction("Index");
        }

        // GET: products/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product product = db.products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: products/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // GET: products/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product product = db.products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            product product = db.products.Find(id);
            db.products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        
    }
}

Ordermanagementsystemdemo/Views/products/Addtocart.cshtml
@model Ordermanagementsystemdemo.product

@{ViewBag.Title = "Addtocart";
}
<br />
<br />
<br />
@using (Html.BeginForm("Addtocart", "products", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
<div class="container">

    <div class="row">
        <div>
            <img style="min-height:200px; width:200px;" src="@Url.Content(Model.image)"/>
        </div>

        <div class="col-lg-8 col-md-8 col-sm-8">
            <h1>ProductName:@Model.name</h1>
            <h1>Price:@Model.price</h1>
            <input type="number" name="qty" value="1" id="qty" min="1" max="5"/>

            <input type="submit" value="Submit" class="btn btn-default"/>
        </div> 

    </div>
</div>
}

Ordermanagementsystemdemo/Views/products/Checkout.cshtml
@{ ViewBag.Title = "Checkout";
        }

<h2>Checkout</h2>

@if (TempData["product"] != null)
{
    <table class="table table-responsive">

        <thead>
            <tr>
                <th>ProductName</th>
                <th>CustomerName</th>
                <th>Price</th>
                     
                
            </tr>
        </thead>


        <tbody>
            @foreach(var item in TempData["product"] as List<Ordermanagementsystemdemo.Models.Cart>)
            {
                <tr>
                    <td>@item.productname</td>
                    <td>ViewBag.customername</td>
                    <td>price</td>
                </tr>
            }
        </tbody>
    </table>
}
else{
    <h2 style="color:red">Cart is Empty...</h2>
    @Html.ActionLink("go back", "Index","products")
}
@if (TempData["product"] != null)
{
    using (Html.BeginForm())
    {
        <input type="submit" value="Order Now" class="btn btn-primary" />
    }
}

Ordermanagementsystemdemo/Views/products/Create.cshtml
@model Ordermanagementsystemdemo.Models.ProductModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create","products", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
        <h4>product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*<input type="file"name="imagefile" required id="file"/>*@
                @Html.TextBox("Imagepath", "", new { type = "file" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Ordermanagementsystemdemo/Views/products/Delete.cshtml
@model Ordermanagementsystemdemo.product

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.weight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.height)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.height)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.availablequentity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.availablequentity)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Ordermanagementsystemdemo/Views/products/Details.cshtml
@model Ordermanagementsystemdemo.product

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.weight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.height)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.height)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.availablequentity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.availablequentity)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Ordermanagementsystemdemo/Views/products/Edit.cshtml
@model Ordermanagementsystemdemo.product

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.weight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.weight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.weight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.height, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.height, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.height, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.image, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.availablequentity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.availablequentity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.availablequentity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Ordermanagementsystemdemo/Views/products/Index.cshtml
@model IEnumerable<Ordermanagementsystemdemo.product>


@{
    ViewBag.Title = "Index";
}
@if (TempData["msg"]!=null)
{
    <div class="alert alert-info">
        <strong>Info!</strong> @TempData["msg"]
    </div>
}


    <div class="row">
    <div class="col-lg-2 col-md-2 col-sm-2">
        <h3 style="color:#808080; font-family:'Arial Rounded MT';text-align:center"><span class="btn btn-info">@Html.ActionLink("Checkout", "Checkout", "products")</span> </h3>  
        <div>
                        @if (ViewBag.roleid == 1)
                        {
                            <span class="btn btn-success">
                                Html.ActionLink("Create New", "Create")</span>
                                }
</div>     
    </div>
</div>

    <div class="row" style="margin-bottom:100px;">
        @foreach (var item in Model)
        {
            <div class="col-lg-4 col-md-4" style="height:200px;margin-top:100px">
                <img class="img img-responsive cimg" src="@Url.Content(item.image)" style="height:110%;width:110%; border-radius:50px 50px 50px 50px" />
                <h3 style="color:#808080; font-family:'Arial Rounded MT';text-align:center">@item.name <small>Rs @item.price</small></h3>
                <h4 style="text-align:center"><span class="btn btn-success">@Html.ActionLink("Add to cart", "Addtocart", new { id = @item.id })</span> </h4>
            </div>
        }

    </div>

    @*<h2>Index</h2>
        <p>
            @Html.ActionLink("Create New", "Create")
        </p>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.name)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.image)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.availablequentity)
                </th>
                <th></th>
            </tr>

        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.name)
                </td>

                <td>
                    <img src="@Url.Content(item.image)" alt="Image"height="80px" width="80px" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.availablequentity)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
                    @Html.ActionLink("Details", "Details", new { id=item.id }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.id })
               </td>
            </tr>
        }

        </table>*@

    @*<div class="row " style="margin-bottom:100px"></div>*@